using System;
using System.Threading.Tasks;

namespace IntelOrca.Biohazard.BioRand
{
    public interface IRandomizerAgentHandler
    {
        /// <summary>
        /// The version of the randomizer, can be a 7 character git hash or a standard version number.
        /// </summary>
        public string BuildVersion { get; }

        /// <summary>
        /// Gets the definition of all the configuration options available for the randomizer.
        /// </summary>
        RandomizerConfigurationDefinition ConfigurationDefinition { get; }

        /// <summary>
        /// Gets the default configuration for the randomizer which is used for the default profile.
        /// </summary>
        RandomizerConfiguration DefaultConfiguration { get; }

        /// <summary>
        /// Gets whether a given generation request can be generated by this particular agent.
        /// </summary>
        /// <param name="queueItem"></param>
        /// <returns></returns>
        Task<bool> CanGenerateAsync(RandomizerAgent.QueueResponseItem queueItem);

        /// <summary>
        /// Generates the given generation request.
        /// </summary>
        /// <param name="queueItem"></param>
        /// <param name="input"></param>
        /// <returns></returns>
        Task<RandomizerOutput> GenerateAsync(RandomizerAgent.QueueResponseItem queueItem, RandomizerInput input);

        /// <summary>
        /// Called when a new status message should be logged.
        /// </summary>
        /// <param name="message"></param>
        void LogInfo(string message);

        /// <summary>
        /// Called when an error message paired with an exception should be logged.
        /// </summary>
        /// <param name="ex"></param>
        /// <param name="message"></param>
        void LogError(Exception ex, string message);
    }
}
